name: Deploy to Existing Compute Engine VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Compute Engine
        run: |
          sudo apt-get update && sudo apt-get install -y npm
          # 실제 GCE 인스턴스 SSH 접속
          gcloud compute ssh instance-20250227-030445 \
            --zone=asia-northeast3-a \
            --command "
              if [ ! -d FE-Server ]; then
                git clone https://github.com/WriteAgain/FE-Server.git;
              fi;
              cd FE-Server;
              curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -;
              sudo apt-get install -y nodejs;
              nvm install --lts;
              git pull origin main;
              npm install;
              npm run dev;
            "
